repos:
  - repo: local
    hooks:
      - id: flowmark
        name: flowmark
        entry: flowmark --auto
        language: system
        types_or: [markdown]
      - id: build-blog
        name: build blog
        entry: make -B all
        language: system
        pass_filenames: false
        files: '^(blog/|Makefile|Gemfile\.lock)'
